package test.selenium;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

public class InsertRequestPostTest {
	private WebDriver driver;

	JavascriptExecutor javas;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		javas = (JavascriptExecutor) driver;

	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void insertRequestPost() {
		driver.get("http://localhost:8080/FinalISPW/LoginWeb.jsp");
		driver.manage().window().setSize(new Dimension(765, 703));
		driver.findElement(By.name("username")).click();
		driver.findElement(By.name("username")).sendKeys("gino");
		driver.findElement(By.name("password")).sendKeys("gino");
		driver.findElement(By.name("action")).click();
		driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(4) > input")).click();
		driver.findElement(By.cssSelector("form > input:nth-child(2)")).click();
		driver.findElement(By.name("title")).click();
		driver.findElement(By.name("title")).sendKeys("nuovo titolo");
		driver.findElement(By.name("description")).sendKeys("nuova descrizione");
		driver.findElement(By.cssSelector("tr:nth-child(5) input")).click();
	}
}
