package test.selenium;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;

import org.openqa.selenium.JavascriptExecutor;


public class ModifyDataTest {
	private WebDriver driver;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void modifyData() {
		driver.get("http://localhost:8080/FinalISPW/LoginWeb.jsp");
		driver.manage().window().setSize(new Dimension(770, 708));
		driver.findElement(By.name("username")).click();
		driver.findElement(By.name("username")).sendKeys("gino");
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("gino");
		driver.findElement(By.name("action")).click();
		driver.findElement(By.cssSelector("tr:nth-child(4) > td:nth-child(2) > input")).click();
		driver.findElement(By.cssSelector("tr:nth-child(3) input")).click();
		driver.findElement(By.name("password")).click();
		driver.findElement(By.name("password")).sendKeys("gino");
		driver.findElement(By.name("email")).click();
		driver.findElement(By.name("email")).sendKeys("franco@franco.com");
		driver.findElement(By.cssSelector("td:nth-child(1) > input")).click();
	}
}
